# Generated by Django 4.0.3 on 2023-04-24 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='date_time',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, null=True, verbose_name='Время создания'),
        ),
        migrations.AddField(
            model_name='questioncomment',
            name='date_time',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, null=True, verbose_name='Время создания'),
        ),
    ]
