# Generated by Django 4.0.3 on 2023-04-26 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0002_answerrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='Рейтинг'),
        ),
    ]
