# Generated by Django 4.0.3 on 2023-04-26 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0003_answer_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerrate',
            name='rate',
            field=models.IntegerField(choices=[(2, 'Ответ полезен'), (-1, 'Бесполезный ответ'), (1, 'Ответ релевантен')], verbose_name='Оценка'),
        ),
    ]
