# Generated by Django 4.2.2 on 2023-06-16 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0004_alter_answerrate_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='was_solution',
            field=models.BooleanField(default=False),
        ),
    ]
