# Generated by Django 4.0.3 on 2023-04-27 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='link',
            field=models.TextField(blank=True, null=True, verbose_name='Ссылка'),
        ),
    ]
